VUID = 'kovarzm'
MACHINE = 'vmp747'

PAGE_TABLE_SPOTIFY = 'SpotifyTable'
COLUMN_FAMILY_SPOTIFY = 'song'
COLUMN_SPOTIFY = 'data'

PAGE_TABLE_SPOTIFY_TRACKS = 'TrackID'
TRACK_COLUMN_FAMILY = 'track'
TRACK_COLUMN = 'data'

BBRD_TABLE = 'Billboard'
BBRD_COLUMN_FAMILY = 'date'
BBRD_COLUMN = 'data'

DEPENDENT_TABLE = 'Dependent'
DEPENDENT_COLUMN_FAMILY = 'song'
DEPENDENT_COLUMN = 'data'

DCOG_TABLE = 'Discogs'
DCOG_COLUMN_FAMILY = 'stuff'
DCOG_COLUMN = 'data'
