VUID = 'kovarzm'
MACHINE = 'vmp747'

PAGE_TABLE_SPOTIFY = 'MusicTable'
COLUMN_FAMILY_SPOTIFY = 'song'
COLUMN_SPOTIFY = 'data'

BBRD_TABLE = 'Billboard'
BBRD_COLUMN_FAMILY = 'date'
BBRD_COLUMN = 'data'

DEPENDENT_TABLE = 'Dependent'
DEPENDENT_COLUMN_FAMILY = 'song'
DEPENDENT_COLUMN = 'data'
